import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  FiZap, FiMessageCircle, FiBarChart2, FiTarget, FiShield,
  FiTrendingUp, FiUsers, FiCode, FiBriefcase, FiAward,
  FiCheckCircle, FiArrowRight, FiCpu, FiLayers, FiBook,
} from 'react-icons/fi';
import { Button } from '../../components/index.js';
import styles from './Home.module.css';

/* ── Animation variants ─────────────────────────────────────────────────────── */
const fadeUp = {
  hidden:  { opacity: 0, y: 40 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.55, ease: 'easeOut' } },
};
const stagger = {
  hidden:  {},
  visible: { transition: { staggerChildren: 0.12 } },
};
const fadeIn = {
  hidden:  { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.45, ease: 'easeOut' } },
};
const scaleIn = {
  hidden:  { opacity: 0, scale: 0.9 },
  visible: { opacity: 1, scale: 1, transition: { duration: 0.4, ease: 'easeOut' } },
};

/* ── Static data ────────────────────────────────────────────────────────────── */
const HOW_IT_WORKS = [
  { step: '01', title: 'Build Your Profile',   body: 'Enter your name, target role, experience, skills, and resume summary. IBM Granite analyses your background holistically.' },
  { step: '02', title: 'Get Your Plan',         body: 'Receive a personalised interview plan — candidate level, difficulty, estimated duration, and question breakdown.' },
  { step: '03', title: 'Choose Your Mode',      body: 'Pick HR, Technical, DSA, Behavioral, or Mixed. The AI adapts every question to your chosen focus area.' },
  { step: '04', title: 'Interview & Get Coached', body: 'Answer questions in real time. After each response, receive an AI Coach Tip with targeted improvement advice.' },
  { step: '05', title: 'Review Your Report',   body: 'Get a full post-interview report: scores, strengths, improvement areas, and a personalised learning roadmap.' },
];

const FEATURES = [
  { icon: <FiZap />,           title: 'AI-Powered Questions',       body: 'Context-aware questions tailored to your role, seniority, and chosen interview mode, generated by IBM watsonx.ai Granite.' },
  { icon: <FiMessageCircle />, title: 'Real-Time Coach Tips',       body: 'After every answer, receive a targeted AI coach tip explaining exactly how to improve before moving on.' },
  { icon: <FiBarChart2 />,     title: 'Deep Performance Reports',   body: 'Session-end scorecards across technical, communication, and confidence dimensions with question-wise breakdowns.' },
  { icon: <FiTarget />,        title: 'Adaptive Difficulty',        body: 'Granite sets difficulty based on your profile — Easy for beginners, Medium for practitioners, Hard for senior engineers.' },
  { icon: <FiShield />,        title: 'Multi-Mode Interviews',      body: 'HR, Technical, DSA, Behavioral, or AI-recommended Mixed mode — you decide how you want to be challenged.' },
  { icon: <FiTrendingUp />,    title: 'Personalised Roadmap',       body: 'Walk away with a prioritised learning roadmap crafted from your specific gaps and the role you are targeting.' },
];

const INTERVIEW_TYPES = [
  { icon: <FiUsers />,    label: 'HR',         desc: 'Motivation, culture fit, and career goals',              color: '#3b82f6' },
  { icon: <FiCode />,     label: 'Technical',  desc: 'Deep dives into your stack and system design',           color: '#8b5cf6' },
  { icon: <FiLayers />,   label: 'DSA',        desc: 'Data structures, algorithms, and coding problem solving', color: '#06b6d4' },
  { icon: <FiBriefcase />,label: 'Behavioral', desc: 'STAR-method situational and competency questions',        color: '#10b981' },
  { icon: <FiAward />,    label: 'Mixed',      desc: 'AI-recommended blend tailored to your profile',           color: '#f59e0b' },
];

const WHY_CHOOSE = [
  'IBM Granite LLM for accurate, nuanced evaluations',
  'Instant coach tips after every answer, not just at the end',
  'Interview plans personalised to candidate level and role',
  'Multiple interview modes for targeted preparation',
  'Comprehensive final report with a learning roadmap',
  'Clean, distraction-free interview environment',
];

const IBM_TECH = [
  { icon: <FiCpu />,         title: 'IBM watsonx.ai',   desc: 'The foundation model platform powering question generation and evaluation.' },
  { icon: <FiShield />,      title: 'IBM Granite',      desc: 'State-of-the-art LLM used for profile analysis, question generation, and scoring.' },
  { icon: <FiBook />,        title: 'Prompt Engineering', desc: 'Carefully engineered system prompts ensure consistent, high-quality JSON-structured outputs.' },
];

/* ── Component ──────────────────────────────────────────────────────────────── */
function Home() {
  const navigate = useNavigate();

  return (
    <motion.div
      className={styles.page}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.3 }}
    >
      {/* Floating background blobs */}
      <div className={styles.bgBlob1} aria-hidden="true" />
      <div className={styles.bgBlob2} aria-hidden="true" />
      <div className={styles.bgBlob3} aria-hidden="true" />

      {/* ── HERO ──────────────────────────────────────────────────────────── */}
      <section className={styles.hero}>
        <motion.div
          className={styles.heroContent}
          variants={stagger}
          initial="hidden"
          animate="visible"
        >
          <motion.div className={styles.heroBadge} variants={fadeIn}>
            IBM watsonx.ai Powered
          </motion.div>
          <motion.h1 className={styles.headline} variants={fadeUp}>
            <span className={styles.highlight}>MockStrive</span>
          </motion.h1>
          <motion.p className={styles.subheadline} variants={fadeUp}>
            Practice Smart. Interview Confidently.
          </motion.p>
          <motion.div className={styles.ctaRow} variants={fadeIn}>
            <Button variant="primary" size="lg" icon={<FiArrowRight />} onClick={() => navigate('/profile')}>
              Start Coaching
            </Button>
            <Button variant="secondary" size="lg" onClick={() => navigate('/about')}>
              Learn More
            </Button>
          </motion.div>
          <motion.div className={styles.heroStats} variants={fadeIn}>
            <div className={styles.stat}><span className={styles.statNum}>5</span><span className={styles.statLabel}>Interview Modes</span></div>
            <div className={styles.statDivider} />
            <div className={styles.stat}><span className={styles.statNum}>IBM</span><span className={styles.statLabel}>Granite LLM</span></div>
            <div className={styles.statDivider} />
            <div className={styles.stat}><span className={styles.statNum}>360°</span><span className={styles.statLabel}>Feedback Reports</span></div>
          </motion.div>
        </motion.div>
      </section>

      {/* ── HOW IT WORKS ──────────────────────────────────────────────────── */}
      <section className={styles.section}>
        <div className={styles.sectionInner}>
          <motion.div
            className={styles.sectionHeader}
            variants={fadeUp}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >
            <span className={styles.sectionLabel}>The Process</span>
            <h2 className={styles.sectionTitle}>How It Works</h2>
            <p className={styles.sectionSubtitle}>Five steps from profile to confident interview performance.</p>
          </motion.div>

          <motion.div
            className={styles.stepsGrid}
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.1 }}
          >
            {HOW_IT_WORKS.map(({ step, title, body }) => (
              <motion.div key={step} className={styles.stepCard} variants={fadeIn}>
                <div className={styles.stepNum}>{step}</div>
                <h3 className={styles.stepTitle}>{title}</h3>
                <p className={styles.stepBody}>{body}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ── FEATURES ──────────────────────────────────────────────────────── */}
      <section className={`${styles.section} ${styles.sectionAlt}`}>
        <div className={styles.sectionInner}>
          <motion.div
            className={styles.sectionHeader}
            variants={fadeUp}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >
            <span className={styles.sectionLabel}>Capabilities</span>
            <h2 className={styles.sectionTitle}>Everything You Need to Prepare</h2>
            <p className={styles.sectionSubtitle}>Comprehensive coaching features, all in one place.</p>
          </motion.div>

          <motion.div
            className={styles.featuresGrid}
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.1 }}
          >
            {FEATURES.map(({ icon, title, body }) => (
              <motion.div
                key={title}
                className={styles.featureCard}
                variants={fadeIn}
                whileHover={{ y: -4, transition: { duration: 0.2 } }}
              >
                <div className={styles.featureIcon}>{icon}</div>
                <h3 className={styles.featureTitle}>{title}</h3>
                <p className={styles.featureBody}>{body}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ── INTERVIEW TYPES ───────────────────────────────────────────────── */}
      <section className={styles.section}>
        <div className={styles.sectionInner}>
          <motion.div
            className={styles.sectionHeader}
            variants={fadeUp}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >
            <span className={styles.sectionLabel}>Modes</span>
            <h2 className={styles.sectionTitle}>Choose Your Interview Type</h2>
            <p className={styles.sectionSubtitle}>Tailor your practice to exactly what you need.</p>
          </motion.div>

          <motion.div
            className={styles.modesGrid}
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.15 }}
          >
            {INTERVIEW_TYPES.map(({ icon, label, desc, color }) => (
              <motion.div
                key={label}
                className={styles.modeCard}
                variants={scaleIn}
                whileHover={{ scale: 1.04, transition: { duration: 0.2 } }}
                style={{ '--mode-color': color }}
              >
                <div className={styles.modeIcon}>{icon}</div>
                <h3 className={styles.modeLabel}>{label}</h3>
                <p className={styles.modeDesc}>{desc}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ── WHY CHOOSE ────────────────────────────────────────────────────── */}
      <section className={`${styles.section} ${styles.sectionAlt}`}>
        <div className={styles.sectionInner}>
          <motion.div
            className={styles.whyGrid}
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.2 }}
          >
            <motion.div className={styles.whyLeft} variants={fadeUp}>
              <span className={styles.sectionLabel}>Advantages</span>
              <h2 className={styles.sectionTitle}>Why Choose AI Coach?</h2>
              <p className={styles.sectionSubtitle}>
                Most interview tools just throw questions at you. AI Coach gives you a structured coaching
                experience — from profile analysis through guided practice to an actionable roadmap.
              </p>
              <Button variant="primary" size="md" icon={<FiArrowRight />} onClick={() => navigate('/profile')}>
                Get Started Free
              </Button>
            </motion.div>

            <motion.ul className={styles.whyList} variants={stagger}>
              {WHY_CHOOSE.map((item) => (
                <motion.li key={item} className={styles.whyItem} variants={fadeIn}>
                  <FiCheckCircle className={styles.whyCheck} aria-hidden="true" />
                  <span>{item}</span>
                </motion.li>
              ))}
            </motion.ul>
          </motion.div>
        </div>
      </section>

      {/* ── IBM TECHNOLOGIES ──────────────────────────────────────────────── */}
      <section className={styles.section}>
        <div className={styles.sectionInner}>
          <motion.div
            className={styles.sectionHeader}
            variants={fadeUp}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >
            <span className={styles.sectionLabel}>Powered By</span>
            <h2 className={styles.sectionTitle}>IBM Technologies</h2>
            <p className={styles.sectionSubtitle}>Enterprise-grade AI at the core of every interaction.</p>
          </motion.div>

          <motion.div
            className={styles.ibmGrid}
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.15 }}
          >
            {IBM_TECH.map(({ icon, title, desc }) => (
              <motion.div key={title} className={styles.ibmCard} variants={fadeIn}>
                <div className={styles.ibmIcon}>{icon}</div>
                <div>
                  <h3 className={styles.ibmTitle}>{title}</h3>
                  <p className={styles.ibmDesc}>{desc}</p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ── FINAL CTA ─────────────────────────────────────────────────────── */}
      <section className={styles.ctaSection}>
        <motion.div
          className={styles.ctaInner}
          variants={stagger}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.3 }}
        >
          <motion.h2 className={styles.ctaTitle} variants={fadeUp}>
            Ready to Ace Your Next Interview?
          </motion.h2>
          <motion.p className={styles.ctaSubtitle} variants={fadeUp}>
            Build your profile in minutes and let IBM Granite create a personalised coaching plan just for you.
          </motion.p>
          <motion.div className={styles.ctaButtons} variants={fadeIn}>
            <Button variant="primary" size="lg" icon={<FiArrowRight />} onClick={() => navigate('/profile')}>
              Start My Coaching Journey
            </Button>
          </motion.div>
        </motion.div>
      </section>
    </motion.div>
  );
}

export default Home;
